---
title: My proposal
subtitle: a study of awesomeness
author: Bob Hette
date: last-modified
affiliation: Department of Biology
comps-proposal: false # or false
committee:
  - name: Julien Martin
    role: supervisor 
  - name: member 2
    role: internal
  - name: member 3
    role: external
degree: PhD # or MSc

# Bibliography style information
bibliography: [proposal_refs.bib, packages.bib]
csl: american-statistical-association.csl

format:
# uncomment if you want this format
  docx: default   # warning title page not formatted correctly
  bio-uo-proposal-pdf:
    toc: true
---

# Introduction

It provides the scientific basis for the study and a (brief) review of
the current literature, the key question(s) for you research leading -up
to the next section about your specific hypotheses or objectives.

This template is developed for Quarto [@quarto]. You can add tables, figures 
and code using R [@base], Python, Julia or Observables.
For more info, go to the Quarto website <https://quarto.org/>

# Research objectives and hypotheses

Specific hypotheses (in the case of hypothesis-testing science) or
objectives (in the case of descriptive science), and the underlying
logic, for each proposed thesis chapter (minimum three for PhD students)

# Proposed methodologies

Include outlines of data collection and data analysis

Outline any special skills, equipment, or techniques that will be
required.

# Expected Products

A list of the (usually 1/3) articles expected for completion of the
MSC/PhD. Think of each as a fantasy abstract.

1.  The Evolution of Human Uniqueness. [Bob Hette & Julien
    Martin.]{.underline}

    There is wide agreement that humans are unique. But it is rarely
    asked: Have they always been unique? In this paper, we derive a
    general uniqueness theorem that states that any unique species must
    have been less unique at some point in the past. This theorem has
    implications for the achievement of world peace.

2.  Niche Construction, Disease Transmission, and Global Warming: Chaos
    Deconstructs the Block Chain. [Bob Hette, Igor Tex & Julien
    Martin]{.underline}

    How many buzz words can be combined in a title? In this paper, we
    find that the natural limit on buzz words in any specific scholarly
    field is always given by the triangular number $T_n$ where $n$ is
    one more than the number of tenured faculty in the field.

3.  A Bayesian Hierarchical Survival Analysis of Counting Sheep. [Bob
    Hette & Julien Martin]{.underline}

    Just like all those other models of counting sheep, but this one
    will be Bayesian.

# Scientific value and rationale for the research

# Course selection

# Schedule

Outline of the calendar for the work. This is necessarily rough and
subject to change. Usually include a Gantt chart

## Completed to date

## Six month plan

# References

::: {refs}
:::